### ISSUE TITLE
Diagnostic Page image error.

### ISSUE THREAD

**Issue by jithukr** [tharianjk/cust1-proj1#4]
there is an error on this line 
document.getElementById(tdata.Diagnostic[i].FSId).src = "img/err.png";
please check this issue on irevapps/inerg server.

**Comment by ashasandeep** [comment]
This happens because we are copying data from eastern instance. The FSes there are moxa1, moxa2 etc.. whereas in inerg instance they are renamed channel1, channel2 etc. however diagnostic response will only have the original names. hence the error. this will be there only in this special case since we are renaming.
